### ISSUE TITLE
[Locations] Error when show detail of room

### ISSUE THREAD

**Issue by firepolo** [claroline/Claroline#1788]
| Q             | A
| ------------- | ---
| Bug report?   | yes/no
| Version?      | master/7.0/etc.

### Situation
When I click on a room I see a blank page. There is an error with a route who isn't exist.

### Location
`/#/desktop/locations/rooms/7470a13f-99df-4176-b740-d64e2e7bfaa3`

### Screenshots
![bug_room_detail](https://user-images.githubusercontent.com/1777148/128306214-0767bc64-91cc-42d6-ab56-3ec5dcbd1eea.png)

**Comment by maieutiquer** [comment]
I confirm that I managed to reproduce in the latest 13.x (13.0.26)

Steps:
1. Install Claroline from scratch
2. Login with an admin account and navigate to Desktop -> Locations -> Rooms
3. Create a new Room with Name and Code
4. Try clicking on the room in order to navigate to it

Expected: You should maybe navigate to the room or see its details (not sure how it was meant to work)

Actual: Blank page and error in the console as per @firepolo's screenshot
