### ISSUE TITLE
[Account] Required fields do not take into account conditions

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#1963]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.1

When a required field depends on another field's value, if the required field is not visible (because its condition is not met), then it's still required and the user cannot proceed

Currently, the administrator is forced to make all fields optional, which is blocking the testing of account creation and conditional fields, and is critical for us

**Comment by YanaMIvanova** [comment]
This is our configuration in Administration

![image](https://user-images.githubusercontent.com/26501599/144840271-b5121077-7f48-41ad-b97d-556d6f489306.png)

![image](https://user-images.githubusercontent.com/26501599/144840405-d6f94932-570e-491e-b0ef-13a5cc231aed.png)

This is the result from our configuration right before clicking on "Create an account" button

![image](https://user-images.githubusercontent.com/26501599/144839833-cdc99f5d-df4f-43d5-8a8f-d03c9cbfb480.png)

These are the errors that we get on account creation when a conditional field is mandatory, but not visible because of its parent

![image](https://user-images.githubusercontent.com/26501599/144839020-6f94c9a4-4ed8-44c1-9d4a-21e8ecab9563.png)

Similar errors appear when we try to close the confirmation modal, even before clicking on "Validate my registration"

![image](https://user-images.githubusercontent.com/26501599/144840005-8a0ac6b9-e67c-42d7-92bd-c5bee24321bd.png)

**Comment by maieutiquer** [comment]
We managed to find the source of the issue, it seems to be caused by the way validations are done, it starts working if we disable validations here:

https://github.com/claroline/Claroline/blob/9fd9122550ca14e54e78868366dc4ad6addfff5c/src/main/core/API/Validator/UserValidator.php#L112

![image](https://user-images.githubusercontent.com/1476049/144875566-8298e952-eb46-4393-9a92-267d86977676.png)

We believe `!ArrayUtils::has($data, 'profile.'.$field['id'])` is not a sufficient check now that we have conditional fields
