### ISSUE TITLE
[Profile] Organization selection does not impact the main organization

### ISSUE THREAD

**Issue by maieutiquer** [claroline/Claroline#2017]
| Q             | A
| ------------- | ---
| Bug report?   | yes
| Version?      | 13.1.4

When a user chooses an organization while creating an account or while modifying their profile, their main organization is still the default one instead of changing to the selected one

**Comment by maieutiquer** [comment]
This is our solution (at least temporarily), let us know what you think and if we should open a PR against this repo as well:
https://github.com/konsept-ch/Claroline/pull/49/files

**Comment by Elorfin** [comment]
This is the expected behavior. When selecting an organization with a profile field, the user is only registered to the organization. It can not change the main organization because : 
- You can add multiple organization fields on the profile and you will not know the one to use as main organization.
- Administrators can directly change the main organization of a user and in this case value for the organization field and the main field organization will be out of sync.

There may be other reasons but this ones are sufficient to keep the current behavior.
