### ISSUE TITLE
Request : Claroline version display

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#653]
Could you display somewhere in the platform, maybe in the footer the actual installed version of Claroline, because i installed several versions, updated some, and have no clue how to know which is which.
And it should be useful for bug tracking, to add the version number to be able to reproduce in the same environment.

**Comment by clarophil** [comment]
You can see in the administration / Package the version number of the core bundle and other packages.

De : stmolivier [mailto:notifications@github.com]
Envoyé : mercredi 25 février 2015 16:44
À : claroline/Claroline
Objet : [Claroline] Request : Claroline version display (#653)


Could you display somewhere in the platform, maybe in the footer the actual installed version of Claroline, because i installed several versions, updated some, and have no clue how to know which is which.
And it should be useful for bug tracking, to add the version number to be able to reproduce in the same environment.

**Comment by ngodfraind** [comment]
Done for the next release.
