### ISSUE TITLE
Bug in Terms and conditions

### ISSUE THREAD

**Issue by stmolivier** [claroline/Claroline#656]
In Claroline 4.22, 
logged in as administrator, 
in the administration menu, in platform parameters, i choose the Terms section.
I set some text in french, activate the terms, and then, when i login as a user, i have the terms text, in french as expected, but the labels are in english and the language at the bottom of the   page is EN.
 If i try to change it to FR, i can't. (But once the conditions are agreed, i log in french.)

**Comment by ngodfraind** [comment]
I wasn't able to reproduce it. I could switch to FR. Things you can do that may fix the poblem:
- double check the locale in the user table is correct (I assume it is) - otherwise it's not going to work
- empty the browser cache - the browser prefered language may be used
- restart the webserver - php sessions

The code used in order to find wich language to use is located in 
- Claroline/CoreBundle/Manager/LocaleManager::getUserLocale

The locale is set in 
- Claroline/CoreBundle/Listener/LocaleSetter::onKernelRequest
