### ISSUE TITLE
Suggestion: install inscript

### ISSUE THREAD

**Issue by phackwer** [claroline/Claroline#679]
It would be easier if the install script changed app/logs, app/cache and app/sessions permissions automatically.

**Comment by ngodfraind** [comment]
This is a good idea. I'll upgrade the script now.

**Comment by arnaudbey** [comment]
Except that there's more than 1 way to handle permissions. chmod, chown, or acl for example...

**Comment by ngodfraind** [comment]
This is a quick and dirty install. Chmod 777 will do the job imo.

2015-05-20 12:02 GMT+02:00 Arnaud Bey <notifications@github.com>:

> Except that there's more than 1 way to handle permissions. chmod, chown,
> or acl for example...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/claroline/Claroline/issues/679#issuecomment-103832315>
> .
>



-- 
Godfraind Nicolas
5, rue de la Carrière
6592 Monceau-Imbrechies
GSM: 0472 94 80 99

**Comment by bizmate** [comment]
I disagree with the custom installation step/sh script. I have seen all the documentation and then found the installation guide based on the caroline/caroline package. 

As per any other bundles and packages the whole suite should be easily installable from composer using install steps in there. I am not an expert on this but what I have seen so far is that the Kernel implemented in this project is customised for some reason and thus make the whole platform a monolitic install that cannot just be included within simple composer steps.

I would prefer a more structured provisioning approach through a configuration or deployment management approach like this puppet step https://github.com/bizmate/vagrant-lamp-symfony/blob/master/puppet/modules/core/manifests/symfony.pp#L75 . This is specific for an acl enabled environment but this could also be detected and appropriate steps reproduced for each operating system or security package

So far i had the following problems:
- the project does not have a provisioning strategy so that a vm could be started in minutes with the whole software, i would suggest a vagrant + puppet/ansible/etc or docker 
- In my puppet file i run the symfony install but ideally in a software like caroline i would prefer a post provisioning deployment step, Bash, capistrano or anything structured and standardised would do
- http://dev.claroline.net/ shows just a standard apache It works page. Fix should be easy enough to at least show to ppl how the software looks like

I hope the above helps, pls let me know when something changes

**Comment by maxailloud** [comment]
@bizmate You're right for the provisioning thing, we may have add something to help installaion of the platform.
But for the deployement step as we don't know the way people would want to deploy the application we cannot provide stuff. In general we add what we use, so if there is not provisionning deployment step it means we don't use tool to deploy, and it's true as for me I just connect by SSH on the server and launch some composer and symfony command, not a big deal.

But we are thinking about a way to make this done automatically, or more quicker and easier.

**Comment by bizmate** [comment]
@maxailloud thanks for the reply. Apologies for hijacking this issue. I have created a separate one to  discuss provisioning and composer install as a separate topic. Pls check https://github.com/claroline/Claroline/issues/685 .
